on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install expect
        run: sudo apt install expect -y
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run script
        working-directory: ./.github/scripts
        run: ./expect_test.sh
