on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install expect
        run: sudo apt install expect -y
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Checking files
        run: echo $(ls)
      - name: Run script
        run: ./.github/scripts/expect_test.sh