on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  On-Merged-PRs-from-test-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "BRANCH=$(echo $GITHUB_HEAD_REF | cut -d '/' -f 1)" >> $GITHUB_ENV
      - name: Do work
        if: env.BRANCH == '@test' && github.event.pull_request.merged == true
        run: echo "WORKS"
      - name: Create folder for private key
        run: mkdir -p ~/.forta
      - name: Write file
        run: echo ${{ secrets.TESTING }} > ./.test/test.txt
      - name: Read file
        run: cat ~/.test/test.txt