on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  On-Merged-PRs-from-test-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
      - name: Printing
        run: echo env.BRANCH
      - name: Do work
        if: env.BRANCH == '@test'
        run: echo "WORKS"